// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-Qh8hnsbGg4ZnlmeOks5avoOzoGNrBs',
    appId: '1:708792518560:web:3404da98a41ebb856c06c5',
    messagingSenderId: '708792518560',
    projectId: 'draughts-online-abc123',
    authDomain: 'draughts-online-abc123.firebaseapp.com',
    storageBucket: 'draughts-online-abc123.firebasestorage.app',
    measurementId: 'G-DF4PZCD5GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChaSPqYkPXBj7H3bfKdPWSkkLjkweMmNs',
    appId: '1:708792518560:android:1db6dacfe4be6e5c6c06c5',
    messagingSenderId: '708792518560',
    projectId: 'draughts-online-abc123',
    storageBucket: 'draughts-online-abc123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQfcOdlc54r3Sg6Rozul-SlH8JAk1t84',
    appId: '1:708792518560:ios:e3767d4550472cf36c06c5',
    messagingSenderId: '708792518560',
    projectId: 'draughts-online-abc123',
    storageBucket: 'draughts-online-abc123.firebasestorage.app',
    iosBundleId: 'com.example.draughtsGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQfcOdlc54r3Sg6Rozul-SlH8JAk1t84',
    appId: '1:708792518560:ios:e3767d4550472cf36c06c5',
    messagingSenderId: '708792518560',
    projectId: 'draughts-online-abc123',
    storageBucket: 'draughts-online-abc123.firebasestorage.app',
    iosBundleId: 'com.example.draughtsGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3-Qh8hnsbGg4ZnlmeOks5avoOzoGNrBs',
    appId: '1:708792518560:web:b081647b3723d5bc6c06c5',
    messagingSenderId: '708792518560',
    projectId: 'draughts-online-abc123',
    authDomain: 'draughts-online-abc123.firebaseapp.com',
    storageBucket: 'draughts-online-abc123.firebasestorage.app',
    measurementId: 'G-X05VPX5WJ1',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA3-Qh8hnsbGg4ZnlmeOks5avoOzoGNrBs',
    appId: '1:708792518560:web:3404da98a41ebb856c06c5',
    messagingSenderId: '708792518560',
    projectId: 'draughts-online-abc123',
    authDomain: 'draughts-online-abc123.firebaseapp.com',
    storageBucket: 'draughts-online-abc123.firebasestorage.app',
  );
}